project:
  type: website
  output-dir: _site
  preview:
    browser: true
  render:
    - "*.qmd"  
    - "*.md"  
    - "!draft/" 
    - "!*.rmd" 
    
website:
  title: "R Pipeline Development Workshop"
  repo-url: https://github.com/Plant-Food-Research-Open/r-pipeline-development-workshop
  repo-actions: [issue]
  page-navigation: true
  description: Content for the R Pipeline Development Workshop.
  open-graph: true
  twitter-card: true
  search:
    limit: 15
    type: overlay
  cookie-consent: false
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
        - pages/index.qmd
      - section: "Tidymodels"
        contents:
        - pages/tidymodels_workshop/1_intro.qmd
        - pages/tidymodels_workshop/2_ml_workflow.qmd
      - section: "Stan"
        contents:
        - pages/stan_workshop/doc.qmd
      - section: "Communications and Community"
        contents:
        - pages/announcements/index.md
        - CODE_OF_CONDUCT.md
        - CONTRIBUTING.md
        
  comments:
    hypothesis:
      theme: clean
      openSidebar: false

theme:
  light: flatly
  dark: darkly

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

execute:
  eval: false
